#!/bin/bash

export dir_in='/array/ssd/msmajdi/experiments/keras/exp6/train/Main'
export dir_out_parent='/array/ssd/msmajdi/experiments/keras/exp6/crossVal/Main'
export x='h'
for v in vimp2_915_07112013_LC vimp2_943_07242013_PA vimp2_ctrl_921_07122013_MP vimp2_ctrl_925_07152013_LS
do

export dir_out=$dir_out_parent/$x
mkdir -p $dir_out/Augments/sd
mv $dir_in/$v $dir_out/
mv $dir_in/Augments/sd/$v\_* $dir_out/Augments/sd/

done
