#!/bin/csh

set Fulldata='/array/ssd/msmajdi/data/preProcessed/7T'
set dataset='All_7T'

cd $Fulldata

foreach vimp ({$dataset}/*)
foreach label( {$vimp}/vtk_rois/*.nii.gz )
echo $label
CopyImageHeaderInformation $vimp/WMnMPRAGE*.nii.gz $label $label 1 1 1 0
end
end











