#!/bin/bash



#nohup python preprocess/run_augment.py -d 1 -sd 2 >> out_Aug_d1 &
#nohup python preprocess/run_augment.py -d 4 -sd 2 >> out_Aug_d4 &

nohup python main.py -g 5 -n all -d 1 -e 60 >> out_3T_Cascade_G5 &
nohup python main.py -g 6 -n all -d 4 -e 60 >> out_7T_Cascade_G6 &




# python otherFuncs/Extra_mergingResults.py -sd 0 -d 4 -g 4 -e 80 
# python otherFuncs/Extra_mergingResults.py -sd 1 -d 4 -g 5 -e 80 
# python otherFuncs/Extra_mergingResults.py -sd 0 -d 1 -g 6 -e 40 
# python otherFuncs/Extra_mergingResults.py -sd 1 -d 1 -g 7 -e 40 


# cd /array/ssd/msmajdi/experiments/keras/
# tar -cvzf All.zip exp*/results/All_*

