#!/bin/tcsh


set dir_in  = '/array/ssd/msmajdi/data/preProcessed/CSFn_WMn/pre-steps/CSFn/full_Image/step0_orig'
set dir_out = '/array/ssd/msmajdi/data/preProcessed/CSFn_WMn/pre-steps/CSFn/full_Image/step1_registered_labels'


cd $dir_in

foreach g (vimp*)
echo $g


cd $dir_in/$g

set IN  = full_T1.nii.gz # crop_t1.nii.gz
set Ref = full_WMn.nii.gz # crop_wmn.nii.gz

antsRegistration  -d 3 --float 0 --output \[aff,affine.nii.gz\] -r \[$IN, $Ref,1\] -t Rigid\[0.1\] --metric MI\[$IN, $Ref,1,32,Regular,0.25\] --convergence \[1000x500x250x100,1e-7,10\] -v -f 8x4x2x1 -s 3x2x1x0vox -v -t Affine\[0.1\] --metric MI\[$IN, $Ref,1,32,Regular,0.25\] --convergence \[1000x500x250x100,5e-8,10\] -f 8x4x2x1 -s 3x2x1x0vox



mkdir $dir_out/$g
mkdir $dir_out/$g/Label

set o = $dir_out/$g

cp $IN $o/$IN


foreach n ('1-THALAMUS' '2-AV' '4-VA' '5-VLa' '6-VLP' '7-VPL' '8-Pul' '9-LGN' '10-MGN' '11-CM' '12-MD-Pf' '13-Hb' '14-MTT')

antsApplyTransforms -d 3 -i Label/$n.nii.gz -r $IN -o $o/Label/$n.nii.gz -t aff0GenericAffine.mat -n NearestNeighbor

end

end






