#!/bin/csh

set dirr='/array/ssd/msmajdi/data/preProcessed/7T/DividedByDisease/ET/Ver2_CopiedHeader'

cd $dirr

foreach vimp (vimp2*)

cd $dirr/{$vimp}/Label/
foreach label(*.nii.gz )
echo $label
CopyImageHeaderInformation ../WMnMPRAGE*.nii.gz $label $label 1 1 1 0
end
end











