#!/bin/tcsh

# export directory = '/array/ssd/msmajdi/data/preProcessed/7T/20priors'
# cd $directory

cd /array/ssd/msmajdi/experiments/keras/exp4_NCrp_7T
rm t*/*/*_PProcessed.nii.gz
rm t*/*/Label/*_PProcessed.nii.gz
rm t*/*/Manual_Delineation_Sanitized/*_PProcessed.nii.gz
# rm t*/*/temp/*_Cropped.nii.gz
rm -r t*/*/temp
rm -r t*/*/Manual_Delineation_Sanitized/temp
# rm -r t*/*/Label/temp


# cd /array/ssd/msmajdi/experiments/keras/exp4_NCrp_SRI/test



