#!/bin/tcsh


set DirCrop = '/RigidRegistration'

set Dir = '/test_case'
cd $Dir


WarpImageMultiTransform 3 WMnMPRAGE_bias_corr.nii.gz WMnMPRAGE_bias_corr_new.nii.gz -R WMnMPRAGE_bias_corr.nii.gz deformation/WMnMPRAGEAffine.txt 


ANTS 3 -m CC\[WMnMPRAGE_bias_corr.nii.gz, $DirCrop/origtemplate.nii.gz ,1,5\] -o linear -i 0 --use-Histogram-Matching --number-of-affine-iterations 10000x10000x10000x10000x10000 --MI-option 32x16000 --rigid-affine false

WarpImageMultiTransform 3 $DirCrop/MyCrop_Template2_Gap20.nii.gz MyCrop2_Gap20_Or.nii.gz -R WMnMPRAGE_bias_corr_new.nii.gz linearAffine.txt












